
test_suite(
    name = "tests",
    tests = [
    "//src/tests/000_hello",
    "//src/tests/002_ada",
    "//src/tests/003_url_parsed",
    "//src/tests/004_url_freq_map",
    "//src/tests/005_url_freq_stats",
    "//src/tests/006_robots",
    "//src/tests/007_urls_days",
    "//src/tests/008_urls_days_db",
    "//src/tests/009_host_db",
    "//src/tests/010_url_db",
    "//src/tests/011_enqueue_loop",
    "//src/tests/014_url_freq_stats_lf",
    "//src/tests/015_crawled_db",
    "//src/tests/016_scheduler",
    "//src/tests/017_load_loop",
    "//src/tests/018_contentd",
    "//src/tests/020_fetch_loop",
    "//src/tests/022_page_db",
    "//src/tests/023_query_loop",
    "//src/tests/024_aho_corasick",
    "//src/tests/025_query_db",
    "//src/tests/026_api_v1",
    "//src/tests/027_scheduler_server"
]
)