
cc_library(
    name="common",
    hdrs=[
        "robots_str.h",
        "test_visits.h",
        "test_urls.h",
        "test_qgs.h",
        "test_pages.h"],
    copts=[],
    deps=[
        "//src/core"
    ],
    visibility = ["//visibility:public"]
)
