
cc_test(
    name = "008_urls_days_db",
    srcs = ["ut_urls_days_db.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/core",
        "//src/ldb"
    ],
    visibility = ["//visibility:public"]
)
