cc_binary(
    name = "test_url_freq_map_kafka",
    srcs = ["test_url_freq_map_kafka.cpp"],
    deps = [
        "//src/core",
        "//src/kafkawrap"
    ],
    copts = [
        "-Isrc/"
    ]
)
