
cc_test(
    name = "020_fetch_loop",
    srcs = ["ut_fetch_loop.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/worker/ut"
    ],
    visibility = ["//visibility:public"]
)
