
cc_test(
    name = "022_page_db",
    srcs = ["ut_page_db.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "@ada//:ada",
        "//src/ldb/ut"
    ],
    visibility = ["//visibility:public"]
)
