
cc_test(
    name = "009_host_db",
    srcs = ["ut_host_db.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/ldb",
        "//src/tests/common"
    ],
    visibility = ["//visibility:public"]
)
