
cc_test(
    name = "006_robots",
    srcs = ["ut_robots.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/core",
        "//src/tests/common"
    ],
    visibility = ["//visibility:public"]
)
