
cc_test(
    name = "005_url_freq_stats",
    srcs = ["ut_url_freq_stats.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/core/ut"
    ],
    visibility = ["//visibility:public"]
)
