
cc_test(
    name = "023_query_loop",
    srcs = ["ut_query_loop.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "@ada//:ada",
        "//src/worker/ut"
    ],
    visibility = ["//visibility:public"]
)
