package(
    default_visibility = ["//visibility:public"]
)

cc_library(
    name = "db",
    hdrs = [
        "IPageDb.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core",
    ],
    copts = [
        "-Isrc/"
    ]
)
