
cc_test(
    name = "003_url_parsed",
    srcs = ["ut_url_parsed.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "@ada//:ada",
        "//src/core"
    ],
    visibility = ["//visibility:public"]
)
