
cc_test(
    name = "017_load_loop",
    srcs = ["ut_load_loop.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/scheduler/default/ut"
    ],
    visibility = ["//visibility:public"]
)
