
cc_test(
    name = "027_scheduler_server",
    srcs = ["ut_scheduler_server.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/scheduler/ut"
    ],
    visibility = ["//visibility:public"]
)
