cc_binary(
    name = "test_robotstxt",
    srcs = ["test_robotstxt.cpp"],
    deps = [
        "//src/core",
        "//contribs/robotstxt:robots"
    ],
    copts = [
        "-Isrc/",
        "-Icontribs/"
    ]
)
