
cc_test(
    name = "015_crawled_db",
    srcs = ["ut_crawled_db.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/ldb/ut"
    ],
    visibility = ["//visibility:public"]
)
