
cc_test(
    name = "026_api_v1",
    srcs = ["ut_api_v1.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/api/v1/ut"
    ],
    visibility = ["//visibility:public"]
)
