cc_binary(
    name = "test_crawl_attempts",
    srcs = ["test_crawl_attempts.cpp"],
    deps = [
        "//src/core",
        "//src/db"
    ],
    copts = [
        "-Isrc/",
        "-Icontribs/"
    ]
)
