
cc_test(
    name = "002_ada",
    srcs = ["ut_ada.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "@ada//:ada"
    ],
    visibility = ["//visibility:public"]
)
