
cc_test(
    name = "016_scheduler",
    srcs = ["ut_scheduler.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/scheduler/ut"
    ],
    visibility = ["//visibility:public"]
)
