
cc_test(
    name = "007_urls_days",
    srcs = ["ut_urls_days.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/core",
        "//src/ldb"
    ],
    visibility = ["//visibility:public"]
)
