cc_binary(
    name = "test_urls_days_db",
    srcs = ["test_urls_days_db.cpp"],
    deps = [
        "//src/core",
        "//src/db"
    ],
    copts = [
        "-Isrc/",
        "-Icontribs/"
    ]
)
