
cc_test(
    name = "004_url_freq_map",
    srcs = ["ut_url_freq_map.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "@ada//:ada",
        "//src/core",
        "//src/tests/common"
    ],
    visibility = ["//visibility:public"]
)
