
cc_test(
    name = "010_url_db",
    srcs = ["ut_url_db.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/ldb"
    ],
    visibility = ["//visibility:public"]
)
