
cc_test(
    name = "014_url_freq_stats_lf",
    srcs = ["ut_url_freq_stats_lf.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/core/ut"
    ],
    visibility = ["//visibility:public"]
)
