
cc_test(
    name = "018_contentd",
    srcs = ["ut_contentd.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/bin/contentd/cli/ut"
    ],
    visibility = ["//visibility:public"]
)
